% cd RawData

preprocesssubj('C1')
preprocesssubj('C2')
preprocesssubj('C3')
preprocesssubj('C4')
preprocesssubj('my')

preprocesssubj('mc')
preprocesssubj('jsa')
preprocesssubj('av')
preprocesssubj('har')
preprocesssubj('hk')
preprocesssubj('ma')

extracteyemovementssubj('C1')
extracteyemovementssubj('C2')
extracteyemovementssubj('C3')
extracteyemovementssubj('C4')
extracteyemovementssubj('my')

extracteyemovementssubj('mc')
extracteyemovementssubj('jsa')
extracteyemovementssubj('av')
extracteyemovementssubj('har')
extracteyemovementssubj('hk')
extracteyemovementssubj('ma')

rereftoobjsubj('C1')
rereftoobjsubj('C2')
rereftoobjsubj('C3')
rereftoobjsubj('C4')
rereftoobjsubj('my')

rereftoobjsubj('mc')
rereftoobjsubj('jsa')
rereftoobjsubj('av')
rereftoobjsubj('har')
rereftoobjsubj('hk')
rereftoobjsubj('ma')
